### ISSUE TITLE
Crash ios

### ISSUE THREAD

**Issue by NicolasCELLA** [jonataslaw/VideoCompress#75]
Hello, I can't compress video on ios only !

video_compress: ^2.1.1
Flutter 1.20.4

No logs, my app closing just

Any idea ?
thx 😇

**Comment by NicolasCELLA** [comment]
<img width="1641" alt="Capture d’écran 2020-11-22 à 11 42 20" src="https://user-images.githubusercontent.com/27723625/99901583-df2f7a00-2cb7-11eb-8834-5991a9eb42f3.png">

On Xcode

**Comment by q200892907** [comment]
me too
Did you solve it?

**Comment by kadnan0900** [comment]
Did you guys find any solution ?

**Comment by NicolasCELLA** [comment]
Yes all videos capture with my iphone 11

**Comment by park1120** [comment]
Exactly same crash error here 😭

**Comment by hungvinh1234** [comment]
Same error, no solution yet !

**Comment by hungvinh1234** [comment]
In my case that error caused by missing meta data of picked video.
I picked video file from AssetEntity.file and it not contain the meta data of video file.
When i change AssetEntity.file =>  AssetEntity.originFile to make it contain EXIF information, the error is solved.
So that, make sure your picked video contain meta data of video.

**Comment by brax10ward** [comment]
> In my case that error caused by missing meta data of picked video.
> I picked video file from AssetEntity.file and it not contain the meta data of video file.
> When i change AssetEntity.file => AssetEntity.originFile to make it contain EXIF information, the error is solved.
> So that, make sure your picked video contain meta data of video.

This also worked for me when using videos from the iOS library but when I am using a file from the camera, which is an `XFile` type it is still throwing the error.

**Comment by GabrielAraujo** [comment]
Have you guys found a solution for this?
